name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${"https://fsc-task-manager-backend.herokuapp.com"}
          heroku_app_name: "sgcafe-task-maneger-front-end"
          heroku_email: "gabrielcafe28@hotmail.com"